name: tpcflu
description: A distraction-free universal Pomodoro timer built with Flutter.
version: 1.0.0
environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  just_audio: ^0.9.46
  window_manager: ^0.4.2
  shared_preferences: ^2.3.0
  flutter_colorpicker: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/tick.wav
