name: tpcflu
description: A distraction-free universal Pomodoro timer built with Flutter.
version: 1.0.0
environment:
  sdk: '>=2.18.0 <4.0.0' # Broadened to support newer Dart versions

dependencies:
  flutter:
    sdk: flutter
  just_audio: ^0.10.4 # Upgraded for Windows audio fixes
  just_audio_media_kit: ^2.1.0
  media_kit_libs_windows_audio: ^1.0.9
  media_kit_libs_linux: ^1.2.1
  shared_preferences: ^2.3.0
  flutter_colorpicker: ^1.1.0
  window_manager: ^0.5.1 # Upgraded for desktop stability
  wakelock_plus: ^1.3.2
  provider: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0 # Upgraded for better linting

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/tick.wav