name: Build and Release TPCFLU
on:
  workflow_dispatch:
jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: gradle
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
          channel: 'stable'
          cache: true
      - run: flutter pub get
      - run: flutter build apk --release
      - run: flutter build appbundle --release
      - uses: actions/upload-artifact@v4
        with:
          name: tpcflu-android
          path: |
            build/app/outputs/flutter-apk/
            build/app/outputs/bundle/release/
          retention-days: 7
  # Other jobs (build-windows, build-ios, etc.) remain as previously provided