name: Build and Release TPCFLU
on:
  workflow_dispatch:
jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: gradle
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
          channel: 'stable'
          cache: true
      - run: flutter pub get
      - name: Build APKs for different architectures
        run: |
          flutter build apk --release --split-per-abi
          flutter build apk --release
    #  - run: flutter build appbundle --release
      - uses: actions/upload-artifact@v4
        with:
          name: tpcflu-android
          path: |
            build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
            build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
            build/app/outputs/flutter-apk/app-x86_64-release.apk
            build/app/outputs/flutter-apk/app-release.apk
     #       build/app/outputs/bundle/release/
          retention-days: 7
