name: Build anDroid
on:
  workflow_dispatch:
  push:
    branches: [ main ]
jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.8'
          channel: 'stable'
      - run: flutter pub get
      - run: flutter build apk --release
      - run: flutter build appbundle --release
      - uses: actions/upload-artifact@v4
        with:
          name: tpcflu-android
          path: |
            build/app/outputs/flutter-apk/
            build/app/outputs/bundle/release/
          retention-days: 7
  release:
    needs: [build-android]
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v'))
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          path: artifacts
      - run: |
          mkdir -p release-assets
          
          cp artifacts/tpcflu-android/flutter-apk/*/release/*.apk release-assets/tpcflu-android.apk
      - uses: softprops/action-gh-release@v2
        with:
          files: release-assets/*
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
